<template>
  <div class="min-h-screen bg-transparent text-white font-sans selection:bg-amber-400 selection:text-slate-900 relative overflow-hidden z-10">
    <header class="relative z-20 flex items-center justify-between px-6 py-4 md:px-12 lg:py-6 max-w-7xl mx-auto">
      <div class="flex items-center space-x-3"><img :src="appStore.siteLogo || '/logo.png'" onerror="this.onerror=null; this.src='/logo.png';" class="h-10 w-10 md:h-12 md:w-12 object-contain drop-shadow-[0_0_10px_rgba(251,191,36,0.5)]" alt="Logo"><span class="text-2xl md:text-3xl font-black italic tracking-widest bg-clip-text text-transparent bg-gradient-to-r from-amber-200 via-yellow-400 to-amber-600 drop-shadow-[0_0_10px_rgba(251,191,36,0.6)]">{{ appStore.siteName || 'XNOW' }}</span></div>
      <div class="flex items-center space-x-4 md:space-x-6"><button @click="appStore.toggleLang" class="text-slate-300 hover:text-white font-bold transition text-sm md:text-base select-none">{{ appStore.lang === 'zh' ? 'EN' : '中' }}</button><router-link v-if="userStore.token" to="/order" class="bg-gradient-to-r from-amber-400 to-yellow-500 hover:from-amber-300 hover:to-yellow-400 text-slate-900 font-black px-5 py-2 md:px-8 md:py-2.5 rounded-full transition transform hover:scale-105 shadow-[0_0_20px_rgba(251,191,36,0.4)]">{{ appStore.t('console') || '控制台' }}</router-link><router-link v-else to="/login" class="bg-gradient-to-r from-amber-400 to-yellow-500 hover:from-amber-300 hover:to-yellow-400 text-slate-900 font-black px-5 py-2 md:px-8 md:py-2.5 rounded-full transition transform hover:scale-105 shadow-[0_0_20px_rgba(251,191,36,0.4)]">{{ appStore.lang === 'zh' ? '登录 / 注册' : 'Login / Register' }}</router-link></div>
    </header>
    <main class="relative z-20 flex flex-col items-center justify-center text-center px-4 pt-20 pb-32 md:pt-32 lg:pt-40 max-w-5xl mx-auto">
      <div class="inline-block mb-6 px-4 py-1.5 rounded-full border border-amber-500/30 bg-amber-500/10 text-amber-400 text-xs md:text-sm font-bold tracking-widest uppercase shadow-[0_0_15px_rgba(251,191,36,0.2)] backdrop-blur-md">{{ appStore.lang === 'zh' ? '🚀 全网最顶级的数字营销流量平台' : '🚀 TOP-TIER SMM PANEL' }}</div>
      <h1 class="text-5xl md:text-7xl lg:text-8xl font-black text-white leading-tight tracking-tight mb-8 drop-shadow-2xl"><span class="text-transparent bg-clip-text bg-gradient-to-r from-white via-slate-200 to-slate-400">Boost Your</span><br /><span class="text-transparent bg-clip-text bg-gradient-to-r from-amber-300 via-yellow-400 to-orange-500 drop-shadow-[0_0_30px_rgba(245,158,11,0.3)]">Social Presence</span></h1>
      <p class="text-slate-300 text-lg md:text-xl max-w-2xl mx-auto mb-12 leading-relaxed font-light drop-shadow-md">{{ appStore.lang === 'zh' ? '提供极速、稳定、安全的全球社交媒体流量服务。全网极致底价，API自动化秒级交付，助力您的数字商业版图火速崛起。' : 'Fast, stable, and secure social media marketing services. Automated delivery at wholesale prices to skyrocket your digital presence.' }}</p>
      <div v-if="userStore.token" class="flex flex-col sm:flex-row items-center justify-center gap-4 w-full sm:w-auto"><router-link to="/order" class="w-full sm:w-auto px-8 py-4 rounded-2xl bg-amber-400 hover:bg-amber-300 text-slate-900 font-black text-base transition transform hover:-translate-y-1 shadow-[0_10px_30px_rgba(251,191,36,0.3)] flex items-center justify-center"><span>{{ appStore.lang === 'zh' ? '📈 涨粉服务' : '📈 SMM Panel' }}</span><svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7l5 5m0 0l-5 5m5-5H6"></path></svg></router-link><router-link v-if="vpnShopEnabled" to="/vpn" class="w-full sm:w-auto px-8 py-4 rounded-2xl bg-emerald-500 hover:bg-emerald-400 text-slate-900 font-black text-base transition transform hover:-translate-y-1 shadow-[0_10px_30px_rgba(16,185,129,0.3)] flex items-center justify-center"><span>{{ appStore.lang === 'zh' ? '🛡️ 安全节点' : '🛡️ Secure VPN' }}</span><svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7l5 5m0 0l-5 5m5-5H6"></path></svg></router-link></div><div v-else class="flex flex-col sm:flex-row items-center justify-center gap-4 w-full sm:w-auto"><router-link to="/login" class="w-full sm:w-auto px-10 py-4 rounded-2xl bg-amber-400 hover:bg-amber-300 text-slate-900 font-black text-lg transition transform hover:-translate-y-1 shadow-[0_10px_30px_rgba(251,191,36,0.3)] flex items-center justify-center">{{ appStore.lang === 'zh' ? '立即注册体验' : 'Get Started Now' }}<svg class="w-5 h-5 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7l5 5m0 0l-5 5m5-5H6"></path></svg></router-link></div>
    </main>
    <section class="relative z-20 bg-slate-900/50 border-t border-slate-800 backdrop-blur-xl py-20 mt-10">
      <div class="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-3 gap-8">
        <div class="bg-slate-800/50 p-8 rounded-3xl border border-slate-700/50 hover:border-amber-500/30 transition group shadow-lg hover:shadow-amber-500/10"><div class="w-14 h-14 bg-amber-500/10 text-amber-400 rounded-2xl flex items-center justify-center text-3xl mb-6 group-hover:scale-110 transition">⚡</div><h3 class="text-xl font-bold text-white mb-3">{{ appStore.lang === 'zh' ? '毫秒级自动交付' : 'Instant Delivery' }}</h3><p class="text-slate-400 text-sm leading-relaxed">{{ appStore.lang === 'zh' ? '系统采用全自动化API对接处理订单，毫秒级响应机制，告别人工漫长等待，让您的业务永远快人一步。' : 'Fully automated API system processing orders in milliseconds. Say goodbye to manual waiting and stay ahead.' }}</p></div>
        <div class="bg-slate-800/50 p-8 rounded-3xl border border-slate-700/50 hover:border-amber-500/30 transition group shadow-lg hover:shadow-blue-500/10"><div class="w-14 h-14 bg-blue-500/10 text-blue-400 rounded-2xl flex items-center justify-center text-3xl mb-6 group-hover:scale-110 transition">💎</div><h3 class="text-xl font-bold text-white mb-3">{{ appStore.lang === 'zh' ? '源头级批发底价' : 'Wholesale Prices' }}</h3><p class="text-slate-400 text-sm leading-relaxed">{{ appStore.lang === 'zh' ? '直连全球顶级一手渠道源头，强力剔除所有中间商差价，确保您获得市场上最具降维打击的极低价格。' : 'Direct connection to global top-tier sources, eliminating middlemen to ensure the most competitive wholesale pricing.' }}</p></div>
        <div class="bg-slate-800/50 p-8 rounded-3xl border border-slate-700/50 hover:border-amber-500/30 transition group shadow-lg hover:shadow-green-500/10"><div class="w-14 h-14 bg-green-500/10 text-green-400 rounded-2xl flex items-center justify-center text-3xl mb-6 group-hover:scale-110 transition">🛡️</div><h3 class="text-xl font-bold text-white mb-3">{{ appStore.lang === 'zh' ? '加密与安全护航' : 'Secure & Stable' }}</h3><p class="text-slate-400 text-sm leading-relaxed">{{ appStore.lang === 'zh' ? '全站部署银行级数据链路加密，多节点集群分发保障，7x24小时全天候巡检监控，平台稳如泰山。' : 'Bank-level data encryption and multi-node cluster deployment with 24/7 monitoring ensure the platform remains rock-solid.' }}</p></div>
      </div>
    </section>
  </div>
</template>
<script setup>
import { ref, onMounted } from 'vue'; import { useAppStore } from '../stores/app'; import { useUserStore } from '../stores/user';
const appStore = useAppStore(); const userStore = useUserStore();
const vpnShopEnabled = ref(true);
onMounted(async () => { appStore.fetchConfig(); try { const r = await fetch('/api/vpn/status'); const d = await r.json(); vpnShopEnabled.value = d.enabled; } catch (e) {} });
</script>
